
services: 
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  frontend:
    build: driver-frontend
    ports: 
      - 3001:3001
    environment:
      NEXTAUTH_URL: http://localhost:3001
      NEXTAUTH_GOOGLE_CLIENT_ID: ""
      NEXTAUTH_GOOGLE_CLIENT_SECRET: ""
      NEXTAUTH_SECRET: ""
    depends_on :
      backend: service_healthy
    
    
  backend:
    build: driver-server
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: ""
    volumes:
      - ./driver-server:/app
      - /app/node_modules
    depends_on:
      postgres: service_healthy
   
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    enviroment:
      - POSTGRES_USER:
      - POSTGRES_PASSWORD:
      - POSTGRES_DB:
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U myuser -d db"]
      interval: 4s
      retries: 4
      timeout: 4s
    

