
services: 
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  frontend:
    build: driver-frontend
    ports: 
      - 3001:3001
    environment:
      NEXTAUTH_URL: http://localhost:3001
      NEXTAUTH_GOOGLE_CLIENT_ID: ""
      NEXTAUTH_GOOGLE_CLIENT_SECRET: ""
      NEXTAUTH_SECRET: "sdfdsfdsf283y892y"
    depends_on :
      - backend
    
    
  backend:
    build: driver-server
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: ""
    volumes:
      - ./driver-server:/app
      - /app/node_modules
   
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    

